apiVersion: skaffold/v2alpha4
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/*
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/user-depl.yaml
      - ./infra/k8s/database/user-service/mongodb-statefulset.yaml
      - ./infra/k8s/debt-depl.yaml
      - ./infra/k8s/database/debt_service/postgresql-statefulset.yaml
      #- ./infra/k8s/order-depl.yaml
      #- ./infra/k8s/debt-depl.yaml
      #- ./infra/k8s/transaction-depl.yaml
      #- ./infra/k8s/rabbitmq/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: 2021199724/user-service
      context: user_service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest : .
    - image: 2021199724/debt-service
      context: debt_service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest : .
    # - image: 2021199724/order-service
    #   context: order_service
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest : .
    # - image: 2021199724/transaction-service
    #   context: transaction_service
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest : .