apiVersion: v1
kind: Secret
metadata:
  name: debt-service
type: Opaque
data:
  POSTGRESQL_USERNAME: P4Sdc2T=
  POSTGRESQL_PASSWORD: P4Sdc2T=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debt-service
  labels:
    app:  debt-service
spec:
  selector:
    matchLabels:
      app:  debt-service
  replicas: 1
  template:
    metadata:
      labels:
        app: debt-service
    spec:
      containers:
      - name: debt-service
        image: 2021199724/debt-service
        ports:
        -  containerPort: 8083
        env:
        - name: POSTGRESQL_HOST
          value: "postgresql-debt-0.postgresql-debt"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tradezerr-secrets
              key: jwtSecret
              optional: false
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: debt-service
              key: POSTGRESQL_USERNAME
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: debt-service
              key: POSTGRESQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: debt-service
  labels:
    app: debt-service
spec:
  selector:
    app: debt-service
  ports:
    - protocol: TCP
      name: debt
      port: 8083
      targetPort: 8083