name: deploy-user-service

on:
  push:
    branches:
      - main
    paths:
      - 'user_service/**'
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tradezerr
      - run: kubectl apply -f infra/k8s/database/user-service/mongodb-statefulset.yaml && kubectl apply -f infra/k8s/user-depl.yaml && kubectl apply -f infra/k8s/ingress-srv.yaml && kubectl apply -f infra/k8s/client-depl.yaml
